---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/user_token":
    post:
      summary: Sign in
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: JWT created
          content: {}
        '404':
          description: Rejected
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
              required:
              - email
              - password
  "/api/v1/users":
    get:
      summary: List users
      tags:
      - Users
      parameters:
      - name: auth
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content: {}
        '401':
          description: Unauthorized
          content: {}
  "/api/v1/users/{id}":
    get:
      summary: Show user by id
      tags:
      - Users
      parameters:
      - name: auth
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content: {}
        '401':
          description: Unauthorized
          content: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3030
