development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: <%= ENV.fetch('ACTION_CABLE_CHANNEL_PREFIX') { "development"} %>

test:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: <%= ENV.fetch('ACTION_CABLE_CHANNEL_PREFIX') { "test"} %>

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: <%= ENV.fetch('ACTION_CABLE_CHANNEL_PREFIX') { "production"} %>
